# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'learn_ui.ui'
#
# Created: Mon Mar 14 12:27:23 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1215, 734)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        Dialog.setFont(font)
        Dialog.setStyleSheet("#add_device_frame {border: 0px; border-radius: 10px; background-color: rgb(217, 217, 217);}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 128))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 35))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.firstLine = QtWidgets.QPushButton(self.frame)
        self.firstLine.setGeometry(QtCore.QRect(10, 100, 281, 23))
        self.firstLine.setObjectName("firstLine")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 149, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setGeometry(QtCore.QRect(1060, 10, 121, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.stop3 = QtWidgets.QPushButton(self.frame)
        self.stop3.setGeometry(QtCore.QRect(300, 100, 59, 23))
        self.stop3.setMinimumSize(QtCore.QSize(10, 0))
        self.stop3.setObjectName("stop3")
        self.groupBox_9 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_9.setGeometry(QtCore.QRect(380, 10, 671, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.playButton = QtWidgets.QPushButton(self.groupBox_9)
        self.playButton.setGeometry(QtCore.QRect(10, 30, 36, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/black_play_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(24, 24))
        self.playButton.setObjectName("playButton")
        self.gotoButton = QtWidgets.QPushButton(self.groupBox_9)
        self.gotoButton.setGeometry(QtCore.QRect(230, 70, 36, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/black_goto_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gotoButton.setIcon(icon1)
        self.gotoButton.setIconSize(QtCore.QSize(24, 24))
        self.gotoButton.setObjectName("gotoButton")
        self.rewindButton = QtWidgets.QPushButton(self.groupBox_9)
        self.rewindButton.setGeometry(QtCore.QRect(10, 70, 36, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/black_rewind_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewindButton.setIcon(icon2)
        self.rewindButton.setIconSize(QtCore.QSize(24, 24))
        self.rewindButton.setObjectName("rewindButton")
        self.pauseButton = QtWidgets.QPushButton(self.groupBox_9)
        self.pauseButton.setGeometry(QtCore.QRect(230, 30, 36, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/black_pause_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon3)
        self.pauseButton.setIconSize(QtCore.QSize(24, 24))
        self.pauseButton.setObjectName("pauseButton")
        self.playLabel = QtWidgets.QLabel(self.groupBox_9)
        self.playLabel.setGeometry(QtCore.QRect(50, 30, 171, 30))
        self.playLabel.setText("")
        self.playLabel.setObjectName("playLabel")
        self.rewindLabel = QtWidgets.QLabel(self.groupBox_9)
        self.rewindLabel.setGeometry(QtCore.QRect(50, 70, 171, 30))
        self.rewindLabel.setText("")
        self.rewindLabel.setObjectName("rewindLabel")
        self.pauseLabel = QtWidgets.QLabel(self.groupBox_9)
        self.pauseLabel.setGeometry(QtCore.QRect(270, 30, 171, 30))
        self.pauseLabel.setText("")
        self.pauseLabel.setObjectName("pauseLabel")
        self.gotoLabel = QtWidgets.QLabel(self.groupBox_9)
        self.gotoLabel.setGeometry(QtCore.QRect(270, 70, 171, 30))
        self.gotoLabel.setText("")
        self.gotoLabel.setObjectName("gotoLabel")
        self.recordButton = QtWidgets.QPushButton(self.groupBox_9)
        self.recordButton.setGeometry(QtCore.QRect(450, 30, 36, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/record_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recordButton.setIcon(icon4)
        self.recordButton.setIconSize(QtCore.QSize(24, 24))
        self.recordButton.setObjectName("recordButton")
        self.recordLabel = QtWidgets.QLabel(self.groupBox_9)
        self.recordLabel.setGeometry(QtCore.QRect(490, 30, 171, 30))
        self.recordLabel.setText("")
        self.recordLabel.setObjectName("recordLabel")
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(1000, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(921, 460))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 351, 31))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.learn_master_volume_ctrl = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.learn_master_volume_ctrl.setObjectName("learn_master_volume_ctrl")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.learn_master_volume_ctrl)
        self.label_master_volume_ctrl = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_master_volume_ctrl.setText("")
        self.label_master_volume_ctrl.setObjectName("label_master_volume_ctrl")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_master_volume_ctrl)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 0, 791, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 261, 33))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.learn_ctrls = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.learn_ctrls.sizePolicy().hasHeightForWidth())
        self.learn_ctrls.setSizePolicy(sizePolicy)
        self.learn_ctrls.setMinimumSize(QtCore.QSize(177, 0))
        self.learn_ctrls.setObjectName("learn_ctrls")
        self.gridLayout_6.addWidget(self.learn_ctrls, 0, 0, 1, 1)
        self.stop1 = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.stop1.setMinimumSize(QtCore.QSize(10, 0))
        self.stop1.setObjectName("stop1")
        self.gridLayout_6.addWidget(self.stop1, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 81, 52))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.ctrlsHorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.ctrlsHorizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.ctrlsHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.ctrlsHorizontalLayout.setObjectName("ctrlsHorizontalLayout")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 120, 261, 41))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.learn_block_bts = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.learn_block_bts.sizePolicy().hasHeightForWidth())
        self.learn_block_bts.setSizePolicy(sizePolicy)
        self.learn_block_bts.setMinimumSize(QtCore.QSize(177, 0))
        self.learn_block_bts.setObjectName("learn_block_bts")
        self.gridLayout_7.addWidget(self.learn_block_bts, 0, 0, 1, 1)
        self.stop2 = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.stop2.setMinimumSize(QtCore.QSize(10, 0))
        self.stop2.setObjectName("stop2")
        self.gridLayout_7.addWidget(self.stop2, 0, 1, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 160, 81, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.btsHorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.btsHorizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.btsHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.btsHorizontalLayout.setObjectName("btsHorizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_3.setGeometry(QtCore.QRect(180, 240, 150, 70))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 139, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.learn_green = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.learn_green.setObjectName("learn_green")
        self.gridLayout_2.addWidget(self.learn_green, 0, 2, 1, 1)
        self.green_vel = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.green_vel.setMaximum(127)
        self.green_vel.setObjectName("green_vel")
        self.gridLayout_2.addWidget(self.green_vel, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_4.setGeometry(QtCore.QRect(340, 240, 150, 70))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 139, 31))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.blink_green_vel = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.blink_green_vel.setMaximum(127)
        self.blink_green_vel.setObjectName("blink_green_vel")
        self.gridLayout_8.addWidget(self.blink_green_vel, 0, 0, 1, 1)
        self.learn_blink_green = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.learn_blink_green.setObjectName("learn_blink_green")
        self.gridLayout_8.addWidget(self.learn_blink_green, 0, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_5.setGeometry(QtCore.QRect(500, 240, 150, 70))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 139, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.red_vel = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.red_vel.setMaximum(127)
        self.red_vel.setObjectName("red_vel")
        self.gridLayout_3.addWidget(self.red_vel, 0, 0, 1, 1)
        self.learn_red = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.learn_red.setObjectName("learn_red")
        self.gridLayout_3.addWidget(self.learn_red, 0, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_6.setGeometry(QtCore.QRect(660, 240, 150, 70))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_6)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 139, 31))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.blink_red_vel = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.blink_red_vel.setMaximum(127)
        self.blink_red_vel.setObjectName("blink_red_vel")
        self.gridLayout_4.addWidget(self.blink_red_vel, 0, 0, 1, 1)
        self.learn_blink_red = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.learn_blink_red.setObjectName("learn_blink_red")
        self.gridLayout_4.addWidget(self.learn_blink_red, 0, 1, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 80, 361, 141))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 191, 101))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.init_command = QtWidgets.QTextEdit(self.groupBox_7)
        self.init_command.setGeometry(QtCore.QRect(10, 30, 131, 71))
        self.init_command.setObjectName("init_command")
        self.sendInitButton = QtWidgets.QPushButton(self.groupBox_7)
        self.sendInitButton.setGeometry(QtCore.QRect(40, 110, 71, 23))
        self.sendInitButton.setObjectName("sendInitButton")
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 240, 161, 70))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_8)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 139, 31))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.black_vel = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.black_vel.setMaximum(127)
        self.black_vel.setObjectName("black_vel")
        self.gridLayout_5.addWidget(self.black_vel, 0, 0, 1, 1)
        self.learn_black = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.learn_black.setObjectName("learn_black")
        self.gridLayout_5.addWidget(self.learn_black, 0, 1, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_10.setGeometry(QtCore.QRect(820, 240, 150, 70))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_10)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(10, 30, 139, 31))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.amber_vel = QtWidgets.QSpinBox(self.gridLayoutWidget_10)
        self.amber_vel.setMaximum(127)
        self.amber_vel.setObjectName("amber_vel")
        self.gridLayout_11.addWidget(self.amber_vel, 0, 0, 1, 1)
        self.learn_amber = QtWidgets.QPushButton(self.gridLayoutWidget_10)
        self.learn_amber.setObjectName("learn_amber")
        self.gridLayout_11.addWidget(self.learn_amber, 0, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_11.setGeometry(QtCore.QRect(980, 240, 150, 70))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_11)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(10, 30, 139, 31))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.blink_amber_vel = QtWidgets.QSpinBox(self.gridLayoutWidget_11)
        self.blink_amber_vel.setMaximum(127)
        self.blink_amber_vel.setObjectName("blink_amber_vel")
        self.gridLayout_12.addWidget(self.blink_amber_vel, 0, 0, 1, 1)
        self.learn_blink_amber = QtWidgets.QPushButton(self.gridLayoutWidget_11)
        self.learn_blink_amber.setObjectName("learn_blink_amber")
        self.gridLayout_12.addWidget(self.learn_blink_amber, 0, 1, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 320, 1181, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_12)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 70, 91, 52))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.scenesHorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.scenesHorizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.scenesHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.scenesHorizontalLayout.setObjectName("scenesHorizontalLayout")
        self.gridLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_12)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(10, 30, 261, 33))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.learn_scenes = QtWidgets.QPushButton(self.gridLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.learn_scenes.sizePolicy().hasHeightForWidth())
        self.learn_scenes.setSizePolicy(sizePolicy)
        self.learn_scenes.setMinimumSize(QtCore.QSize(177, 0))
        self.learn_scenes.setObjectName("learn_scenes")
        self.gridLayout_14.addWidget(self.learn_scenes, 0, 0, 1, 1)
        self.stop4 = QtWidgets.QPushButton(self.gridLayoutWidget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop4.sizePolicy().hasHeightForWidth())
        self.stop4.setSizePolicy(sizePolicy)
        self.stop4.setMinimumSize(QtCore.QSize(10, 0))
        self.stop4.setObjectName("stop4")
        self.gridLayout_14.addWidget(self.stop4, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New Device"))
        self.label.setText(_translate("Dialog", "Device Name"))
        self.firstLine.setText(_translate("Dialog", "Learn First line"))
        self.label_8.setText(_translate("Dialog", "Start / Stop Buttons"))
        self.stop3.setText(_translate("Dialog", "Stop"))
        self.groupBox_9.setTitle(_translate("Dialog", "Transport"))
        self.playButton.setToolTip(_translate("Dialog", "Play"))
        self.gotoButton.setToolTip(_translate("Dialog", "Go to"))
        self.rewindButton.setToolTip(_translate("Dialog", "Rewind"))
        self.pauseButton.setToolTip(_translate("Dialog", "Pause"))
        self.recordButton.setToolTip(_translate("Dialog", "Pause"))
        self.groupBox.setTitle(_translate("Dialog", "Master volume"))
        self.learn_master_volume_ctrl.setText(_translate("Dialog", "Master Volume Controller"))
        self.groupBox_2.setTitle(_translate("Dialog", "Clips volume per line"))
        self.learn_ctrls.setText(_translate("Dialog", "Learn controllers"))
        self.stop1.setText(_translate("Dialog", "Stop"))
        self.learn_block_bts.setText(_translate("Dialog", "Learn line buttons"))
        self.stop2.setText(_translate("Dialog", "Stop"))
        self.groupBox_3.setTitle(_translate("Dialog", "Green Color"))
        self.learn_green.setText(_translate("Dialog", "Test"))
        self.groupBox_4.setTitle(_translate("Dialog", "Blink Green Color"))
        self.learn_blink_green.setText(_translate("Dialog", "Test"))
        self.groupBox_5.setTitle(_translate("Dialog", "Red Color"))
        self.learn_red.setText(_translate("Dialog", "Test"))
        self.groupBox_6.setTitle(_translate("Dialog", "Blink Red Color"))
        self.learn_blink_red.setText(_translate("Dialog", "Test"))
        self.groupBox_7.setTitle(_translate("Dialog", "Init command (optional)"))
        self.label_2.setText(_translate("Dialog", "Init commands must be entered as 3 decimal values separated by comma and one command per line.\n"
"example:\n"
"176, 0, 0\n"
"176, 0, 40"))
        self.sendInitButton.setText(_translate("Dialog", "Send"))
        self.groupBox_8.setTitle(_translate("Dialog", "Black Color (light off)"))
        self.learn_black.setText(_translate("Dialog", "Test"))
        self.groupBox_10.setTitle(_translate("Dialog", "Amber Color"))
        self.learn_amber.setText(_translate("Dialog", "Test"))
        self.groupBox_11.setTitle(_translate("Dialog", "Blink Amber Color"))
        self.learn_blink_amber.setText(_translate("Dialog", "Test"))
        self.groupBox_12.setTitle(_translate("Dialog", "Scenes"))
        self.learn_scenes.setText(_translate("Dialog", "Learn scenes"))
        self.stop4.setText(_translate("Dialog", "Stop"))

import gui_rc
