# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'superboucle/add_clip_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(375, 210)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(240, 70, 111, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.audio_group = QtWidgets.QGroupBox(Dialog)
        self.audio_group.setGeometry(QtCore.QRect(10, 10, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.audio_group.setFont(font)
        self.audio_group.setObjectName("audio_group")
        self.audioLoadButton = QtWidgets.QRadioButton(self.audio_group)
        self.audioLoadButton.setGeometry(QtCore.QRect(10, 60, 141, 21))
        self.audioLoadButton.setObjectName("audioLoadButton")
        self.audioNewButton = QtWidgets.QRadioButton(self.audio_group)
        self.audioNewButton.setGeometry(QtCore.QRect(10, 30, 131, 21))
        self.audioNewButton.setObjectName("audioNewButton")
        self.midi_group = QtWidgets.QGroupBox(Dialog)
        self.midi_group.setGeometry(QtCore.QRect(10, 110, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.midi_group.setFont(font)
        self.midi_group.setObjectName("midi_group")
        self.midiNewButton = QtWidgets.QRadioButton(self.midi_group)
        self.midiNewButton.setGeometry(QtCore.QRect(10, 30, 131, 21))
        self.midiNewButton.setObjectName("midiNewButton")
        self.midiLoadButton = QtWidgets.QRadioButton(self.midi_group)
        self.midiLoadButton.setGeometry(QtCore.QRect(10, 60, 141, 21))
        self.midiLoadButton.setObjectName("midiLoadButton")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.audio_group.setTitle(_translate("Dialog", "Audio"))
        self.audioLoadButton.setText(_translate("Dialog", "Load file..."))
        self.audioNewButton.setText(_translate("Dialog", "Empty clip"))
        self.midi_group.setTitle(_translate("Dialog", "MIDI"))
        self.midiNewButton.setText(_translate("Dialog", "Empty clip"))
        self.midiLoadButton.setText(_translate("Dialog", "Load file..."))
