# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'superboucle/gui_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 915)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {background-color: black;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("#centralwidget {background-color: Black;}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_out = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_out.sizePolicy().hasHeightForWidth())
        self.frame_out.setSizePolicy(sizePolicy)
        self.frame_out.setMinimumSize(QtCore.QSize(236, 875))
        self.frame_out.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_out.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_out.setObjectName("frame_out")
        self.label_7 = QtWidgets.QLabel(self.frame_out)
        self.label_7.setGeometry(QtCore.QRect(50, 0, 120, 85))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/icons/icons/logo.png"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.frame_in = QtWidgets.QFrame(self.frame_out)
        self.frame_in.setGeometry(QtCore.QRect(0, 90, 236, 776))
        self.frame_in.setStyleSheet("#frame_in {\n"
"background-color: rgb(175, 178, 178);}")
        self.frame_in.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_in.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_in.setObjectName("frame_in")
        self.master_volume = QSuperDial(self.frame_in)
        self.master_volume.setGeometry(QtCore.QRect(90, 10, 60, 60))
        self.master_volume.setMaximumSize(QtCore.QSize(60, 60))
        self.master_volume.setStyleSheet("background-color: rgb(223, 27, 130);\n"
"color: black;")
        self.master_volume.setMaximum(256)
        self.master_volume.setObjectName("master_volume")
        self.label_6 = QtWidgets.QLabel(self.frame_in)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(160, 6, 89);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.frame_clip = QtWidgets.QFrame(self.frame_in)
        self.frame_clip.setGeometry(QtCore.QRect(10, 280, 216, 486))
        self.frame_clip.setStyleSheet("#frame_clip {background-color: rgb(223, 223, 223);}")
        self.frame_clip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_clip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_clip.setObjectName("frame_clip")
        self.clip_name = QtWidgets.QLineEdit(self.frame_clip)
        self.clip_name.setGeometry(QtCore.QRect(0, 0, 216, 31))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.clip_name.setFont(font)
        self.clip_name.setStyleSheet("#clip_name {background-color: black; color: rgb(255, 253, 24);}")
        self.clip_name.setAlignment(QtCore.Qt.AlignCenter)
        self.clip_name.setObjectName("clip_name")
        self.label_5 = QtWidgets.QLabel(self.frame_clip)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 71, 19))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.clip_volume = QSuperDial(self.frame_clip)
        self.clip_volume.setEnabled(True)
        self.clip_volume.setGeometry(QtCore.QRect(90, 35, 51, 51))
        self.clip_volume.setStyleSheet("background-color: rgb(241, 248, 0);\n"
"color: black;")
        self.clip_volume.setMaximum(256)
        self.clip_volume.setSingleStep(1)
        self.clip_volume.setObjectName("clip_volume")
        self.label_4 = QtWidgets.QLabel(self.frame_clip)
        self.label_4.setGeometry(QtCore.QRect(10, 105, 111, 19))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.beat_diviser = QtWidgets.QSpinBox(self.frame_clip)
        self.beat_diviser.setGeometry(QtCore.QRect(130, 95, 71, 41))
        self.beat_diviser.setStyleSheet("QSpinBox::up-button { width: 40px; }\n"
"QSpinBox::down-button { width: 40px; }\n"
"QSpinBox { border : 0px; border-radius: 2px}")
        self.beat_diviser.setMinimum(1)
        self.beat_diviser.setMaximum(999)
        self.beat_diviser.setObjectName("beat_diviser")
        self.clip_description = QtWidgets.QLabel(self.frame_clip)
        self.clip_description.setGeometry(QtCore.QRect(10, 370, 196, 41))
        self.clip_description.setStyleSheet("color: white;\n"
"background-color: black;\n"
"border-radius: 2px;")
        self.clip_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.clip_description.setObjectName("clip_description")
        self.deleteButton = QtWidgets.QPushButton(self.frame_clip)
        self.deleteButton.setGeometry(QtCore.QRect(99, 450, 101, 23))
        self.deleteButton.setObjectName("deleteButton")
        self.exportButton = QtWidgets.QPushButton(self.frame_clip)
        self.exportButton.setGeometry(QtCore.QRect(100, 420, 101, 23))
        self.exportButton.setObjectName("exportButton")
        self.normalizeButton = QtWidgets.QPushButton(self.frame_clip)
        self.normalizeButton.setGeometry(QtCore.QRect(10, 450, 80, 23))
        self.normalizeButton.setObjectName("normalizeButton")
        self.revertButton = QtWidgets.QPushButton(self.frame_clip)
        self.revertButton.setGeometry(QtCore.QRect(10, 420, 81, 23))
        self.revertButton.setObjectName("revertButton")
        self.groupBox = QtWidgets.QGroupBox(self.frame_clip)
        self.groupBox.setGeometry(QtCore.QRect(10, 310, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.mute_group = QtWidgets.QSpinBox(self.groupBox)
        self.mute_group.setGeometry(QtCore.QRect(10, 25, 43, 23))
        self.mute_group.setObjectName("mute_group")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_clip)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 191, 91))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 161, 74))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.frame_offset = QtWidgets.QSpinBox(self.formLayoutWidget_4)
        self.frame_offset.setMinimum(-4410000)
        self.frame_offset.setMaximum(4410000)
        self.frame_offset.setObjectName("frame_offset")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frame_offset)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.beat_offset = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_4)
        self.beat_offset.setEnabled(True)
        self.beat_offset.setMaximum(99.0)
        self.beat_offset.setSingleStep(0.01)
        self.beat_offset.setObjectName("beat_offset")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.beat_offset)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_clip)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 240, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.output = QtWidgets.QComboBox(self.groupBox_3)
        self.output.setGeometry(QtCore.QRect(10, 30, 141, 23))
        self.output.setObjectName("output")
        self.playButton = QtWidgets.QPushButton(self.frame_in)
        self.playButton.setGeometry(QtCore.QRect(55, 150, 36, 30))
        self.playButton.setStyleSheet("QPushButton {background-color: rgb(0, 0, 0);}\n"
"QPushButton:pressed {background-color: rgb(98, 98, 98);}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/white_play_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon1)
        self.playButton.setIconSize(QtCore.QSize(24, 24))
        self.playButton.setObjectName("playButton")
        self.pauseButton = QtWidgets.QPushButton(self.frame_in)
        self.pauseButton.setGeometry(QtCore.QRect(100, 150, 36, 30))
        self.pauseButton.setStyleSheet("QPushButton {background-color: rgb(0, 0, 0);}\n"
"QPushButton:pressed {background-color: rgb(98, 98, 98);}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/white_pause_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon2)
        self.pauseButton.setIconSize(QtCore.QSize(24, 24))
        self.pauseButton.setObjectName("pauseButton")
        self.rewindButton = QtWidgets.QPushButton(self.frame_in)
        self.rewindButton.setGeometry(QtCore.QRect(10, 150, 36, 30))
        self.rewindButton.setStyleSheet("QPushButton {background-color: rgb(0, 0, 0);}\n"
"QPushButton:pressed {background-color: rgb(98, 98, 98);}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/white_rewind_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewindButton.setIcon(icon3)
        self.rewindButton.setIconSize(QtCore.QSize(24, 24))
        self.rewindButton.setObjectName("rewindButton")
        self.bbtLabel = QtWidgets.QLabel(self.frame_in)
        self.bbtLabel.setGeometry(QtCore.QRect(27, 80, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.bbtLabel.setFont(font)
        self.bbtLabel.setStyleSheet("background-color: black;\n"
"color: rgb(0, 255, 0);")
        self.bbtLabel.setText("")
        self.bbtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bbtLabel.setObjectName("bbtLabel")
        self.gotoButton = QtWidgets.QPushButton(self.frame_in)
        self.gotoButton.setGeometry(QtCore.QRect(190, 150, 36, 30))
        self.gotoButton.setStyleSheet("QPushButton {background-color: rgb(0, 0, 0);}\n"
"QPushButton:pressed {background-color: rgb(98, 98, 98);}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/white_goto_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gotoButton.setIcon(icon4)
        self.gotoButton.setIconSize(QtCore.QSize(24, 24))
        self.gotoButton.setObjectName("gotoButton")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_in)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 190, 214, 113))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(160, 6, 89);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.bpm = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.bpm.setMinimum(1.0)
        self.bpm.setMaximum(260.0)
        self.bpm.setProperty("value", 120.0)
        self.bpm.setObjectName("bpm")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bpm)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(160, 6, 89);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.beat_per_bar = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.beat_per_bar.setMinimum(1)
        self.beat_per_bar.setProperty("value", 4)
        self.beat_per_bar.setObjectName("beat_per_bar")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.beat_per_bar)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(160, 6, 89);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.gotoTarget = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.gotoTarget.setMinimum(1)
        self.gotoTarget.setMaximum(999999999)
        self.gotoTarget.setObjectName("gotoTarget")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gotoTarget)
        self.recordButton = QtWidgets.QPushButton(self.frame_in)
        self.recordButton.setGeometry(QtCore.QRect(145, 150, 36, 30))
        self.recordButton.setStyleSheet("QPushButton {background-color: rgb(0, 0, 0);}\n"
"QPushButton:pressed {background-color: rgb(98, 98, 98);}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/record_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recordButton.setIcon(icon5)
        self.recordButton.setIconSize(QtCore.QSize(24, 24))
        self.recordButton.setObjectName("recordButton")
        self.verticalLayout.addWidget(self.frame_out)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_out = QtWidgets.QGridLayout()
        self.gridLayout_out.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_out.setContentsMargins(12, -1, -1, -1)
        self.gridLayout_out.setObjectName("gridLayout_out")
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_out.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_out.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_out.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_out)
        self.horizontalLayout.setStretch(1, 9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDevice = QtWidgets.QMenu(self.menubar)
        self.menuDevice.setObjectName("menuDevice")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionAdd_Device = QtWidgets.QAction(MainWindow)
        self.actionAdd_Device.setObjectName("actionAdd_Device")
        self.actionFullScreen = QtWidgets.QAction(MainWindow)
        self.actionFullScreen.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionFullScreen.setObjectName("actionFullScreen")
        self.actionManage_Devices = QtWidgets.QAction(MainWindow)
        self.actionManage_Devices.setObjectName("actionManage_Devices")
        self.actionPlaylist_Editor = QtWidgets.QAction(MainWindow)
        self.actionPlaylist_Editor.setObjectName("actionPlaylist_Editor")
        self.actionPort_Manager = QtWidgets.QAction(MainWindow)
        self.actionPort_Manager.setObjectName("actionPort_Manager")
        self.actionScene_Manager = QtWidgets.QAction(MainWindow)
        self.actionScene_Manager.setObjectName("actionScene_Manager")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionQuit)
        self.menuDevice.addAction(self.actionAdd_Device)
        self.menuDevice.addAction(self.actionManage_Devices)
        self.menuDevice.addSeparator()
        self.menuView.addAction(self.actionFullScreen)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionScene_Manager)
        self.menuView.addAction(self.actionPlaylist_Editor)
        self.menuView.addAction(self.actionPort_Manager)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Super Boucle"))
        self.label_6.setText(_translate("MainWindow", "Master"))
        self.label_5.setText(_translate("MainWindow", "Volume"))
        self.label_4.setText(_translate("MainWindow", "Beat Amount"))
        self.clip_description.setText(_translate("MainWindow", "Description"))
        self.deleteButton.setText(_translate("MainWindow", "Delete Clip"))
        self.exportButton.setText(_translate("MainWindow", "Export Sample"))
        self.normalizeButton.setText(_translate("MainWindow", "Normalize"))
        self.revertButton.setText(_translate("MainWindow", "Revert"))
        self.groupBox.setTitle(_translate("MainWindow", "Mute Group"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Clip Offset"))
        self.label_2.setText(_translate("MainWindow", "Sample"))
        self.label.setText(_translate("MainWindow", "Beat"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Output"))
        self.playButton.setToolTip(_translate("MainWindow", "Play"))
        self.pauseButton.setToolTip(_translate("MainWindow", "Pause"))
        self.rewindButton.setToolTip(_translate("MainWindow", "Rewind"))
        self.gotoButton.setToolTip(_translate("MainWindow", "Go to"))
        self.label_10.setText(_translate("MainWindow", "BPM"))
        self.label_11.setText(_translate("MainWindow", "Beat per bar"))
        self.label_12.setText(_translate("MainWindow", "Goto Position"))
        self.recordButton.setToolTip(_translate("MainWindow", "Pause"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDevice.setTitle(_translate("MainWindow", "Device"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionAdd_Device.setText(_translate("MainWindow", "Add Device..."))
        self.actionFullScreen.setText(_translate("MainWindow", "FullScreen"))
        self.actionFullScreen.setShortcut(_translate("MainWindow", "F11"))
        self.actionManage_Devices.setText(_translate("MainWindow", "Manage Devices..."))
        self.actionManage_Devices.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionPlaylist_Editor.setText(_translate("MainWindow", "Playlist Editor"))
        self.actionPlaylist_Editor.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionPort_Manager.setText(_translate("MainWindow", "Port Manager"))
        self.actionPort_Manager.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionScene_Manager.setText(_translate("MainWindow", "Scene Manager"))
        self.actionScene_Manager.setShortcut(_translate("MainWindow", "Ctrl+E"))

from superboucle.qsuperdial import QSuperDial
from superboucle import gui_rc
