# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'superboucle/set_tempo_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(265, 220)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(80, 160, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.bpm = QtWidgets.QDoubleSpinBox(Dialog)
        self.bpm.setGeometry(QtCore.QRect(150, 20, 71, 26))
        self.bpm.setObjectName("bpm")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 25, 54, 17))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 75, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.set_current_button = QtWidgets.QPushButton(Dialog)
        self.set_current_button.setGeometry(QtCore.QRect(10, 120, 111, 25))
        self.set_current_button.setObjectName("set_current_button")
        self.forgot_button = QtWidgets.QPushButton(Dialog)
        self.forgot_button.setGeometry(QtCore.QRect(130, 120, 121, 25))
        self.forgot_button.setObjectName("forgot_button")
        self.sample_per_beat = QtWidgets.QSpinBox(Dialog)
        self.sample_per_beat.setGeometry(QtCore.QRect(150, 70, 71, 26))
        self.sample_per_beat.setObjectName("sample_per_beat")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "BPM"))
        self.label_2.setText(_translate("Dialog", "Sample per beat"))
        self.set_current_button.setText(_translate("Dialog", "Set Current BPM"))
        self.forgot_button.setText(_translate("Dialog", "Forgot Tempo"))
