# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'superboucle/tape_manager_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1008, 638)
        self.calibrateButton = QtWidgets.QPushButton(Dialog)
        self.calibrateButton.setGeometry(QtCore.QRect(30, 20, 80, 26))
        self.calibrateButton.setObjectName("calibrateButton")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 89, 186, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lengthLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lengthLabel.setObjectName("lengthLabel")
        self.gridLayout.addWidget(self.lengthLabel, 1, 0, 1, 1)
        self.speedLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.speedLabel.setObjectName("speedLabel")
        self.gridLayout.addWidget(self.speedLabel, 0, 0, 1, 1)
        self.lengthValue = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lengthValue.setObjectName("lengthValue")
        self.gridLayout.addWidget(self.lengthValue, 1, 1, 1, 1)
        self.speedValue = QtWidgets.QLabel(self.gridLayoutWidget)
        self.speedValue.setObjectName("speedValue")
        self.gridLayout.addWidget(self.speedValue, 0, 1, 1, 1)
        self.positionLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.positionLabel.setObjectName("positionLabel")
        self.gridLayout.addWidget(self.positionLabel, 2, 0, 1, 1)
        self.positionValue = QtWidgets.QLabel(self.gridLayoutWidget)
        self.positionValue.setObjectName("positionValue")
        self.gridLayout.addWidget(self.positionValue, 2, 1, 1, 1)
        self.panicButton = QtWidgets.QPushButton(Dialog)
        self.panicButton.setGeometry(QtCore.QRect(130, 20, 80, 26))
        self.panicButton.setObjectName("panicButton")
        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setGeometry(QtCore.QRect(350, 20, 80, 26))
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(Dialog)
        self.stopButton.setGeometry(QtCore.QRect(440, 20, 80, 26))
        self.stopButton.setObjectName("stopButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.calibrateButton.setText(_translate("Dialog", "Calibrate"))
        self.lengthLabel.setText(_translate("Dialog", "Tape Length"))
        self.speedLabel.setText(_translate("Dialog", "Speed"))
        self.lengthValue.setText(_translate("Dialog", "56.7 cm"))
        self.speedValue.setText(_translate("Dialog", "17.5 cm/s"))
        self.positionLabel.setText(_translate("Dialog", "Position"))
        self.positionValue.setText(_translate("Dialog", "12.5 cm\n"
"57 %"))
        self.panicButton.setText(_translate("Dialog", "Panic !"))
        self.startButton.setText(_translate("Dialog", "Start"))
        self.stopButton.setText(_translate("Dialog", "Stop"))
